apiVersion: v1
kind: Secret
metadata:
  name: {{ include "buy-ticket.fullname" . }}-secret
  labels:
    {{- include "buy-ticket.labels" . | nindent 4 }}
type: Opaque
stringData:
  REDIS_PASSWORD: {{ .Values.redis.password | quote }}
  PAYMENT_MOCK_MERCHANT_ID: {{ .Values.payment.mock.merchantID | quote }}
  PAYMENT_MOCK_HASH_KEY: {{ .Values.payment.mock.hashKey | quote }}
  PAYMENT_MOCK_HASH_IV: {{ .Values.payment.mock.hashIV | quote }}
